name = "CorrDCA"
uuid = "71fba74b-94bb-4624-adc3-6f657ac12af8"
authors = ["Andrea Pagnani"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
